import "../assets/icon/fontawesome/css/all.min.css";
import "./globals.css";
import "./grid.css";
import "./customSwiper.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import { Poppins } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
